from bs4 import BeautifulSoup
import typing
import os

from bookmark import Bookmark
from bookmarks_extractor import BookmarksExtractor


class MarkdownGenerator:
    def generate_markdown(self, bookmarks: typing.List[Bookmark]) -> str:
        markdown_table = self.generate_markdown_table(bookmarks)
        script_name = os.path.basename(__file__)
        return f"# Bookmarks\n\n{markdown_table}\n\nGenerated by [{script_name}]"

    def generate_markdown_table(self, bookmarks: typing.List[Bookmark]) -> str:
        lines = []
        lines.append("| # | Domain | Date | Bookmark |")
        lines.append("|---|--------|------|----------|")
        for index, bookmark in enumerate(bookmarks):
            line = self.generate_row(index, bookmark)
            lines.append(line)
        return "\n".join(lines)

    def generate_row(self, index: int, bookmark: Bookmark) -> str:
        domain = bookmark.get_domain()
        readable_date = bookmark.get_readable_date()
        return f"| {index} | {domain} | {readable_date} | [{bookmark.text}]({bookmark.href}) |"
